runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

env_variables:
  CLOUDSQL_CONNECTION_NAME: restful-cc:europe-west1:restful
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD:

libraries:
- name: MySQLdb
  version: latest